package provider

import mock "github.com/stretchr/testify/mock"
import models "github.com/convox/praxis/provider/models"

// MockProvider is an autogenerated mock type for the Provider type
type MockProvider struct {
	mock.Mock
}

// TableList provides a mock function with given fields:
func (_m *MockProvider) TableList() (models.Tables, error) {
	ret := _m.Called()

	var r0 models.Tables
	if rf, ok := ret.Get(0).(func() models.Tables); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(models.Tables)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

var _ Provider = (*MockProvider)(nil)
